// <auto-generated />
using System;
using MesSpc.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MesSpc.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508040029_V3_MasterDataAndUploads")]
    partial class V3_MasterDataAndUploads
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.AlertEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ActualValue")
                        .HasColumnType("float");

                    b.Property<int>("AlertType")
                        .HasColumnType("int");

                    b.Property<int?>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrectiveAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InspectionItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<int?>("MeasurementValueId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ResponsibleUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RootCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AlertEvents");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.AttributeMeasurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CharacteristicId")
                        .HasColumnType("int");

                    b.Property<int?>("DefectCount")
                        .HasColumnType("int");

                    b.Property<int?>("DefectQty")
                        .HasColumnType("int");

                    b.Property<int?>("InspectedQty")
                        .HasColumnType("int");

                    b.Property<string>("LotNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("PartProcessCharacteristicId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<int>("SampleNo")
                        .HasColumnType("int");

                    b.Property<int?>("UnitCount")
                        .HasColumnType("int");

                    b.Property<Guid>("UploadBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PartProcessCharacteristicId");

                    b.HasIndex("UploadBatchId");

                    b.HasIndex("PartId", "ProcessId", "CharacteristicId", "MeasuredAt");

                    b.ToTable("AttributeMeasurements");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.ControlChartCategory", b =>
                {
                    b.Property<int>("ChartCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChartCategoryId"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChartGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.HasKey("ChartCategoryId");

                    b.HasIndex("ChartGroupId", "CategoryCode")
                        .IsUnique();

                    b.ToTable("ControlChartCategories");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.ControlChartGroup", b =>
                {
                    b.Property<int>("ChartGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChartGroupId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.HasKey("ChartGroupId");

                    b.HasIndex("GroupCode")
                        .IsUnique();

                    b.ToTable("ControlChartGroups");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.ControlChartType", b =>
                {
                    b.Property<int>("ChartTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChartTypeId"));

                    b.Property<int>("ChartCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ChartTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChartTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormulaConfigJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("RequiredSampleSize")
                        .HasColumnType("int");

                    b.HasKey("ChartTypeId");

                    b.HasIndex("ChartCategoryId");

                    b.HasIndex("ChartTypeCode")
                        .IsUnique();

                    b.ToTable("ControlChartTypes");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.FormulaDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormulaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FormulaCode")
                        .IsUnique();

                    b.ToTable("FormulaDefinitions");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.InspectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<bool>("IsSpcEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Lcl")
                        .HasColumnType("float");

                    b.Property<double?>("Lsl")
                        .HasColumnType("float");

                    b.Property<double?>("TargetValue")
                        .HasColumnType("float");

                    b.Property<double?>("Ucl")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Usl")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.ToTable("InspectionItems");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MachineId"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MachineId");

                    b.HasIndex("MachineCode")
                        .IsUnique();

                    b.HasIndex("ProcessId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.MeasurementBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LotNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int?>("StationOperationSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LotNo");

                    b.HasIndex("SerialNo");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("MeasurementBatches");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.MeasurementValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InspectionItemId")
                        .HasColumnType("int");

                    b.Property<int>("SampleNo")
                        .HasColumnType("int");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("bit");

                    b.Property<double?>("ValueNumeric")
                        .HasColumnType("float");

                    b.Property<string>("ValueText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("MeasurementValues");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Specification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PartId");

                    b.HasIndex("PartNo")
                        .IsUnique();

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.PartProcessCharacteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("CL")
                        .HasColumnType("float");

                    b.Property<int>("CharacteristicId")
                        .HasColumnType("int");

                    b.Property<int?>("ChartTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<double?>("LCL")
                        .HasColumnType("float");

                    b.Property<double?>("LSL")
                        .HasColumnType("float");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<int?>("RuleGroupId")
                        .HasColumnType("int");

                    b.Property<int>("SampleSize")
                        .HasColumnType("int");

                    b.Property<double?>("TargetValue")
                        .HasColumnType("float");

                    b.Property<double?>("UCL")
                        .HasColumnType("float");

                    b.Property<double?>("USL")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("ChartTypeId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("RuleGroupId");

                    b.HasIndex("PartId", "ProcessId", "CharacteristicId")
                        .IsUnique();

                    b.ToTable("PartProcessCharacteristics");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.Process", b =>
                {
                    b.Property<int>("ProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ProcessCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProcessId");

                    b.HasIndex("ProcessCode")
                        .IsUnique();

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.ProductStationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InspectionItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SampleSize")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "StationId", "InspectionItemId")
                        .IsUnique();

                    b.ToTable("ProductStationItems");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.QualityCharacteristic", b =>
                {
                    b.Property<int>("CharacteristicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacteristicId"));

                    b.Property<string>("CharacteristicCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CharacteristicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DefaultChartTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpcEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharacteristicId");

                    b.HasIndex("CharacteristicCode")
                        .IsUnique();

                    b.HasIndex("DefaultChartTypeId");

                    b.ToTable("QualityCharacteristics");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.SpcCalculationResult", b =>
                {
                    b.Property<long>("SpcResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SpcResultId"));

                    b.Property<long?>("AttributeMeasurementId")
                        .HasColumnType("bigint");

                    b.Property<double?>("CL")
                        .HasColumnType("float");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChartTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DataCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOutOfControl")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOutOfSpec")
                        .HasColumnType("bit");

                    b.Property<double?>("LCL")
                        .HasColumnType("float");

                    b.Property<double?>("LSL")
                        .HasColumnType("float");

                    b.Property<int>("PartProcessCharacteristicId")
                        .HasColumnType("int");

                    b.Property<int?>("RuleGroupId")
                        .HasColumnType("int");

                    b.Property<string>("StatisticName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("StatisticValue")
                        .HasColumnType("float");

                    b.Property<double?>("UCL")
                        .HasColumnType("float");

                    b.Property<double?>("USL")
                        .HasColumnType("float");

                    b.Property<Guid>("UploadBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("VariableMeasurementId")
                        .HasColumnType("bigint");

                    b.Property<string>("ViolatedRulesJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpcResultId");

                    b.HasIndex("ChartTypeId");

                    b.HasIndex("UploadBatchId");

                    b.HasIndex("PartProcessCharacteristicId", "CalculatedAt");

                    b.ToTable("SpcCalculationResults");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.SpcRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RuleConfigJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RuleGroupId")
                        .HasColumnType("int");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RuleId");

                    b.HasIndex("RuleGroupId", "RuleCode")
                        .IsUnique();

                    b.ToTable("SpcRules");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.SpcRuleGroup", b =>
                {
                    b.Property<int>("RuleGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleGroupId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("RuleGroupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RuleGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RuleGroupId");

                    b.HasIndex("RuleGroupCode")
                        .IsUnique();

                    b.ToTable("SpcRuleGroups");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StationCode")
                        .IsUnique();

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.StationOperationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LotNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LotNo");

                    b.HasIndex("SerialNo");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("StationOperationSessions");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.UploadBatch", b =>
                {
                    b.Property<Guid>("UploadBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ErrorRows")
                        .HasColumnType("int");

                    b.Property<string>("ImportStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.Property<string>("UploadType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValidRows")
                        .HasColumnType("int");

                    b.HasKey("UploadBatchId");

                    b.ToTable("UploadBatches");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.UploadDetail", b =>
                {
                    b.Property<long>("UploadDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UploadDetailId"));

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowNo")
                        .HasColumnType("int");

                    b.Property<Guid>("UploadBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UploadDetailId");

                    b.HasIndex("UploadBatchId", "RowNo")
                        .IsUnique();

                    b.ToTable("UploadDetails");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.UploadError", b =>
                {
                    b.Property<long>("UploadErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UploadErrorId"));

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RowNo")
                        .HasColumnType("int");

                    b.Property<Guid>("UploadBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("UploadDetailId")
                        .HasColumnType("bigint");

                    b.HasKey("UploadErrorId");

                    b.HasIndex("UploadBatchId");

                    b.HasIndex("UploadDetailId");

                    b.ToTable("UploadErrors");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.VariableMeasurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CharacteristicId")
                        .HasColumnType("int");

                    b.Property<string>("LotNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("MeasuredValue")
                        .HasColumnType("float");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("PartProcessCharacteristicId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<int>("SampleNo")
                        .HasColumnType("int");

                    b.Property<string>("SerialNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UploadBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PartProcessCharacteristicId");

                    b.HasIndex("UploadBatchId");

                    b.HasIndex("PartId", "ProcessId", "CharacteristicId", "MeasuredAt");

                    b.ToTable("VariableMeasurements");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ActualQty")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedEndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlannedQty")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PlannedStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkOrderNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderNo")
                        .IsUnique();

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.AttributeMeasurement", b =>
                {
                    b.HasOne("MesSpc.Api.Domain.Entities.PartProcessCharacteristic", null)
                        .WithMany()
                        .HasForeignKey("PartProcessCharacteristicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MesSpc.Api.Domain.Entities.UploadBatch", null)
                        .WithMany()
                        .HasForeignKey("UploadBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.ControlChartCategory", b =>
                {
                    b.HasOne("MesSpc.Api.Domain.Entities.ControlChartGroup", null)
                        .WithMany()
                        .HasForeignKey("ChartGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.ControlChartType", b =>
                {
                    b.HasOne("MesSpc.Api.Domain.Entities.ControlChartCategory", null)
                        .WithMany()
                        .HasForeignKey("ChartCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.Machine", b =>
                {
                    b.HasOne("MesSpc.Api.Domain.Entities.Process", null)
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.MeasurementValue", b =>
                {
                    b.HasOne("MesSpc.Api.Domain.Entities.MeasurementBatch", null)
                        .WithMany("Values")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.PartProcessCharacteristic", b =>
                {
                    b.HasOne("MesSpc.Api.Domain.Entities.QualityCharacteristic", null)
                        .WithMany()
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MesSpc.Api.Domain.Entities.ControlChartType", null)
                        .WithMany()
                        .HasForeignKey("ChartTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MesSpc.Api.Domain.Entities.Part", null)
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MesSpc.Api.Domain.Entities.Process", null)
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MesSpc.Api.Domain.Entities.SpcRuleGroup", null)
                        .WithMany()
                        .HasForeignKey("RuleGroupId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.QualityCharacteristic", b =>
                {
                    b.HasOne("MesSpc.Api.Domain.Entities.ControlChartType", null)
                        .WithMany()
                        .HasForeignKey("DefaultChartTypeId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.SpcCalculationResult", b =>
                {
                    b.HasOne("MesSpc.Api.Domain.Entities.ControlChartType", null)
                        .WithMany()
                        .HasForeignKey("ChartTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MesSpc.Api.Domain.Entities.PartProcessCharacteristic", null)
                        .WithMany()
                        .HasForeignKey("PartProcessCharacteristicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MesSpc.Api.Domain.Entities.UploadBatch", null)
                        .WithMany()
                        .HasForeignKey("UploadBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.SpcRule", b =>
                {
                    b.HasOne("MesSpc.Api.Domain.Entities.SpcRuleGroup", null)
                        .WithMany()
                        .HasForeignKey("RuleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.UploadDetail", b =>
                {
                    b.HasOne("MesSpc.Api.Domain.Entities.UploadBatch", null)
                        .WithMany()
                        .HasForeignKey("UploadBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.UploadError", b =>
                {
                    b.HasOne("MesSpc.Api.Domain.Entities.UploadBatch", null)
                        .WithMany()
                        .HasForeignKey("UploadBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MesSpc.Api.Domain.Entities.UploadDetail", null)
                        .WithMany()
                        .HasForeignKey("UploadDetailId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.VariableMeasurement", b =>
                {
                    b.HasOne("MesSpc.Api.Domain.Entities.PartProcessCharacteristic", null)
                        .WithMany()
                        .HasForeignKey("PartProcessCharacteristicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MesSpc.Api.Domain.Entities.UploadBatch", null)
                        .WithMany()
                        .HasForeignKey("UploadBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MesSpc.Api.Domain.Entities.MeasurementBatch", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
