SELECT TABLE_NAME, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('VariableMeasurements', 'AttributeMeasurements', 'UploadBatches', 'AlertEvents')
ORDER BY TABLE_NAME, ORDINAL_POSITION;
