using MesSpc.Api.Domain.Entities;
using MesSpc.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace MesSpc.Api.Services.TestData;

public class DatabaseSeeder(AppDbContext db)
{
    public async Task EnsureFormulaDefinitionsAsync()
    {
        var required = new Dictionary<string, string>
        {
            ["AVG"] = "AVG(values)",
            ["STDEV"] = "STDEV(values)",
            ["RANGE"] = "RANGE(values)",
            ["MAX"] = "MAX(values)",
            ["MIN"] = "MIN(values)",
            ["COUNT"] = "COUNT(values)",
            ["SUM"] = "SUM(values)",
            ["CP"] = "CP(values,USL,LSL)",
            ["CPK"] = "CPK(values,USL,LSL)"
        };
        var exists = await db.FormulaDefinitions.Select(x => x.FormulaCode).ToListAsync();
        var toAdd = required
            .Where(kv => !exists.Contains(kv.Key))
            .Select(kv => new FormulaDefinition
            {
                FormulaCode = kv.Key,
                DisplayName = kv.Key,
                Expression = kv.Value,
                IsBuiltIn = true,
                IsActive = true
            }).ToList();
        if (toAdd.Count == 0) return;
        db.FormulaDefinitions.AddRange(toAdd);
        await db.SaveChangesAsync();
    }

    public async Task SaveProductsStationsItemsAsync(List<Product> products, List<Station> stations, List<InspectionItem> items)
    {
        db.Products.AddRange(products);
        db.Stations.AddRange(stations);
        db.InspectionItems.AddRange(items);
        await db.SaveChangesAsync();
    }

    public async Task SaveProductStationItemsAsync(List<Product> products, List<Station> stations, List<InspectionItem> items)
    {
        var links = new List<ProductStationItem>();
        foreach (var p in products)
        foreach (var s in stations)
        foreach (var i in items)
        {
            links.Add(new ProductStationItem
            {
                ProductId = p.Id,
                StationId = s.Id,
                InspectionItemId = i.Id,
                SampleSize = 5,
                IsActive = true
            });
        }
        db.ProductStationItems.AddRange(links);
        await db.SaveChangesAsync();
    }

    public async Task SaveWorkOrdersAsync(List<WorkOrder> workOrders)
    {
        db.WorkOrders.AddRange(workOrders);
        await db.SaveChangesAsync();
    }

    public async Task SaveBatchesAsync(List<MeasurementBatch> batches)
    {
        db.MeasurementBatches.AddRange(batches);
        await db.SaveChangesAsync();
    }

    public async Task<int> CreateAlertsForAnomaliesAsync(List<MeasurementBatch> batches)
    {
        var alerts = new List<AlertEvent>();
        var itemMap = await db.InspectionItems.ToDictionaryAsync(x => x.Id);
        foreach (var batch in batches)
        {
            foreach (var v in batch.Values.Where(x => x.ValueNumeric.HasValue))
            {
                if (!itemMap.TryGetValue(v.InspectionItemId, out var item)) continue;
                var x = v.ValueNumeric!.Value;
                if ((item.Usl.HasValue && x > item.Usl.Value) || (item.Lsl.HasValue && x < item.Lsl.Value))
                {
                    alerts.Add(new AlertEvent
                    {
                        OccurredAt = DateTime.UtcNow,
                        PartId = batch.ProductId, // Mapped from legacy ProductId
                        ProcessId = batch.StationId, // Mapped from legacy StationId
                        CharacteristicId = v.InspectionItemId, // Mapped from legacy InspectionItemId
                        ActualValue = x,
                        // BatchId and MeasurementValueId removed from AlertEvent
                        Message = $"{TestDataTags.E2ePrefix}Spec violation generated by seeder",
                        Status = "Open",
                        IsAcknowledged = false
                    });
                }
            }
        }

        if (alerts.Count > 0)
        {
            db.AlertEvents.AddRange(alerts);
            await db.SaveChangesAsync();
        }
        return alerts.Count;
    }

    public async Task<ClearTestDataResponse> ClearAllTestDataAsync(string? runId = null)
    {
        var useRunId = !string.IsNullOrWhiteSpace(runId);
        var testProducts = await db.Products
            .Where(x => x.ProductCode.StartsWith(TestDataTags.TestPrefix) && (!useRunId || x.ProductCode.Contains(runId!)))
            .Select(x => x.Id).ToListAsync();
        var testStations = await db.Stations
            .Where(x => x.StationCode.StartsWith(TestDataTags.TestPrefix) && (!useRunId || x.StationCode.Contains(runId!)))
            .Select(x => x.Id).ToListAsync();
        var testItems = await db.InspectionItems
            .Where(x => x.ItemCode.StartsWith(TestDataTags.TestPrefix) && (!useRunId || x.ItemCode.Contains(runId!)))
            .Select(x => x.Id).ToListAsync();
        var testWorkOrders = await db.WorkOrders
            .Where(x => x.WorkOrderNo.StartsWith(TestDataTags.TestPrefix) && (!useRunId || x.WorkOrderNo.Contains(runId!)))
            .Select(x => x.Id).ToListAsync();
        var testBatchIds = await db.MeasurementBatches
            .Where(x =>
                ((x.BatchNo.StartsWith(TestDataTags.TestPrefix)) && (!useRunId || x.BatchNo.Contains(runId!))) ||
                ((x.LotNo != null && x.LotNo.StartsWith(TestDataTags.TestPrefix)) && (!useRunId || x.LotNo.Contains(runId!))) ||
                ((x.SerialNo != null && x.SerialNo.StartsWith(TestDataTags.TestPrefix)) && (!useRunId || x.SerialNo.Contains(runId!))) ||
                (x.WorkOrderId.HasValue && testWorkOrders.Contains(x.WorkOrderId.Value)))
            .Select(x => x.Id).ToListAsync();

        var testValueIds = await db.MeasurementValues.Where(x => testBatchIds.Contains(x.BatchId)).Select(x => x.Id).ToListAsync();
        var testAlertIds = await db.AlertEvents
            .Where(x =>
                (x.Message.StartsWith(TestDataTags.E2ePrefix)) ||
                (testProducts.Contains(x.PartId)))
            .Select(x => x.Id).ToListAsync();
        var testSessionIds = await db.StationOperationSessions
            .Where(x => testWorkOrders.Contains(x.WorkOrderId) || (x.LotNo != null && x.LotNo.StartsWith(TestDataTags.TestPrefix)))
            .Select(x => x.Id).ToListAsync();

        db.AlertEvents.RemoveRange(db.AlertEvents.Where(x => testAlertIds.Contains(x.Id)));
        db.MeasurementValues.RemoveRange(db.MeasurementValues.Where(x => testValueIds.Contains(x.Id)));
        db.MeasurementBatches.RemoveRange(db.MeasurementBatches.Where(x => testBatchIds.Contains(x.Id)));
        db.StationOperationSessions.RemoveRange(db.StationOperationSessions.Where(x => testSessionIds.Contains(x.Id)));
        db.ProductStationItems.RemoveRange(db.ProductStationItems.Where(x =>
            testProducts.Contains(x.ProductId) || testStations.Contains(x.StationId) || testItems.Contains(x.InspectionItemId)));
        db.WorkOrders.RemoveRange(db.WorkOrders.Where(x => testWorkOrders.Contains(x.Id)));
        db.InspectionItems.RemoveRange(db.InspectionItems.Where(x => testItems.Contains(x.Id)));
        db.Stations.RemoveRange(db.Stations.Where(x => testStations.Contains(x.Id)));
        db.Products.RemoveRange(db.Products.Where(x => testProducts.Contains(x.Id)));
        await db.SaveChangesAsync();

        return new ClearTestDataResponse(
            testProducts.Count,
            testStations.Count,
            testItems.Count,
            testWorkOrders.Count,
            testSessionIds.Count,
            testBatchIds.Count,
            testValueIds.Count,
            testAlertIds.Count);
    }

    public async Task EnsureSpcRulesAsync()
    {
        var groupCode = "WECO-DEFAULT";
        var group = await db.SpcRuleGroups.FirstOrDefaultAsync(x => x.RuleGroupCode == groupCode);
        if (group == null)
        {
            group = new SpcRuleGroup
            {
                RuleGroupCode = groupCode,
                RuleGroupName = "Western Electric Standard Rules",
                Description = "Default WECO rules for SPC",
                IsEnabled = true
            };
            db.SpcRuleGroups.Add(group);
            await db.SaveChangesAsync();
        }

        var existingRules = await db.SpcRules.Where(x => x.RuleGroupId == group.Id).Select(x => x.RuleCode).ToListAsync();

        var rulesToAdd = new List<SpcRule>();
        if (!existingRules.Contains("WECO-1"))
            rulesToAdd.Add(new SpcRule { RuleGroupId = group.Id, RuleCode = "WECO-1", RuleName = "1 point > 3 sigma from center line", Priority = 10 });
        if (!existingRules.Contains("WECO-2"))
            rulesToAdd.Add(new SpcRule { RuleGroupId = group.Id, RuleCode = "WECO-2", RuleName = "9 points in a row on same side of center line", RuleConfigJson = "{\"RequiredPoints\": 9}", Priority = 20 });
        if (!existingRules.Contains("WECO-3"))
            rulesToAdd.Add(new SpcRule { RuleGroupId = group.Id, RuleCode = "WECO-3", RuleName = "6 points in a row, all increasing or all decreasing", RuleConfigJson = "{\"RequiredPoints\": 6}", Priority = 30 });
        if (!existingRules.Contains("WECO-4"))
            rulesToAdd.Add(new SpcRule { RuleGroupId = group.Id, RuleCode = "WECO-4", RuleName = "14 points in a row, alternating up and down", RuleConfigJson = "{\"RequiredPoints\": 14}", Priority = 40 });

        if (rulesToAdd.Count > 0)
        {
            db.SpcRules.AddRange(rulesToAdd);
            await db.SaveChangesAsync();
        }
    }
}

