using MesSpc.Api.Domain.Entities;
using MesSpc.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace MesSpc.Api.Services.TestData;

public class DatabaseSeeder(AppDbContext db)
{
    public async Task EnsureFormulaDefinitionsAsync()
    {
        var required = new Dictionary<string, string>
        {
            ["AVG"] = "AVG(values)",
            ["STDEV"] = "STDEV(values)",
            ["RANGE"] = "RANGE(values)",
            ["MAX"] = "MAX(values)",
            ["MIN"] = "MIN(values)",
            ["COUNT"] = "COUNT(values)",
            ["SUM"] = "SUM(values)",
            ["CP"] = "CP(values,USL,LSL)",
            ["CPK"] = "CPK(values,USL,LSL)"
        };
        var exists = await db.FormulaDefinitions.Select(x => x.FormulaCode).ToListAsync();
        var toAdd = required
            .Where(kv => !exists.Contains(kv.Key))
            .Select(kv => new FormulaDefinition
            {
                FormulaCode = kv.Key,
                DisplayName = kv.Key,
                Expression = kv.Value,
                IsBuiltIn = true,
                IsActive = true
            }).ToList();
        if (toAdd.Count == 0) return;
        db.FormulaDefinitions.AddRange(toAdd);
        await db.SaveChangesAsync();
    }

    public async Task SaveProductsStationsItemsAsync(List<Product> products, List<Station> stations, List<InspectionItem> items)
    {
        db.Products.AddRange(products);
        db.Stations.AddRange(stations);
        db.InspectionItems.AddRange(items);
        await db.SaveChangesAsync();
    }

    public async Task SaveProductStationItemsAsync(List<Product> products, List<Station> stations, List<InspectionItem> items)
    {
        var links = new List<ProductStationItem>();
        foreach (var p in products)
        foreach (var s in stations)
        foreach (var i in items)
        {
            links.Add(new ProductStationItem
            {
                ProductId = p.Id,
                StationId = s.Id,
                InspectionItemId = i.Id,
                SampleSize = 5,
                IsActive = true
            });
        }
        db.ProductStationItems.AddRange(links);
        await db.SaveChangesAsync();
    }

    public async Task SaveWorkOrdersAsync(List<WorkOrder> workOrders)
    {
        db.WorkOrders.AddRange(workOrders);
        await db.SaveChangesAsync();
    }

    public async Task SaveBatchesAsync(List<MeasurementBatch> batches)
    {
        db.MeasurementBatches.AddRange(batches);
        await db.SaveChangesAsync();
    }

    public async Task<int> CreateAlertsForAnomaliesAsync(List<MeasurementBatch> batches)
    {
        var alerts = new List<AlertEvent>();
        var itemMap = await db.InspectionItems.ToDictionaryAsync(x => x.Id);
        foreach (var batch in batches)
        {
            foreach (var v in batch.Values.Where(x => x.ValueNumeric.HasValue))
            {
                if (!itemMap.TryGetValue(v.InspectionItemId, out var item)) continue;
                var x = v.ValueNumeric!.Value;
                if ((item.Usl.HasValue && x > item.Usl.Value) || (item.Lsl.HasValue && x < item.Lsl.Value))
                {
                    alerts.Add(new AlertEvent
                    {
                        OccurredAt = DateTime.UtcNow,
                        PartId = batch.ProductId, // Mapped from legacy ProductId
                        ProcessId = batch.StationId, // Mapped from legacy StationId
                        CharacteristicId = v.InspectionItemId, // Mapped from legacy InspectionItemId
                        ActualValue = x,
                        // BatchId and MeasurementValueId removed from AlertEvent
                        Message = $"{TestDataTags.E2ePrefix}Spec violation generated by seeder",
                        Status = "Open",
                        IsAcknowledged = false
                    });
                }
            }
        }

        if (alerts.Count > 0)
        {
            db.AlertEvents.AddRange(alerts);
            await db.SaveChangesAsync();
        }
        return alerts.Count;
    }

    public async Task<ClearTestDataResponse> ClearAllTestDataAsync(string? runId = null)
    {
        var useRunId = !string.IsNullOrWhiteSpace(runId);
        var testProducts = await db.Products
            .Where(x => x.ProductCode.StartsWith(TestDataTags.TestPrefix) && (!useRunId || x.ProductCode.Contains(runId!)))
            .Select(x => x.Id).ToListAsync();
        var testStations = await db.Stations
            .Where(x => x.StationCode.StartsWith(TestDataTags.TestPrefix) && (!useRunId || x.StationCode.Contains(runId!)))
            .Select(x => x.Id).ToListAsync();
        var testItems = await db.InspectionItems
            .Where(x => x.ItemCode.StartsWith(TestDataTags.TestPrefix) && (!useRunId || x.ItemCode.Contains(runId!)))
            .Select(x => x.Id).ToListAsync();
        var testWorkOrders = await db.WorkOrders
            .Where(x => x.WorkOrderNo.StartsWith(TestDataTags.TestPrefix) && (!useRunId || x.WorkOrderNo.Contains(runId!)))
            .Select(x => x.Id).ToListAsync();
        var testBatchIds = await db.MeasurementBatches
            .Where(x =>
                ((x.BatchNo.StartsWith(TestDataTags.TestPrefix)) && (!useRunId || x.BatchNo.Contains(runId!))) ||
                ((x.LotNo != null && x.LotNo.StartsWith(TestDataTags.TestPrefix)) && (!useRunId || x.LotNo.Contains(runId!))) ||
                ((x.SerialNo != null && x.SerialNo.StartsWith(TestDataTags.TestPrefix)) && (!useRunId || x.SerialNo.Contains(runId!))) ||
                (x.WorkOrderId.HasValue && testWorkOrders.Contains(x.WorkOrderId.Value)))
            .Select(x => x.Id).ToListAsync();

        var testValueIds = await db.MeasurementValues.Where(x => testBatchIds.Contains(x.BatchId)).Select(x => x.Id).ToListAsync();
        var testAlertIds = await db.AlertEvents
            .Where(x =>
                (x.Message.StartsWith(TestDataTags.E2ePrefix)) ||
                (testProducts.Contains(x.PartId)))
            .Select(x => x.Id).ToListAsync();
        var testSessionIds = await db.StationOperationSessions
            .Where(x => testWorkOrders.Contains(x.WorkOrderId) || (x.LotNo != null && x.LotNo.StartsWith(TestDataTags.TestPrefix)))
            .Select(x => x.Id).ToListAsync();

        db.AlertEvents.RemoveRange(db.AlertEvents.Where(x => testAlertIds.Contains(x.Id)));
        db.MeasurementValues.RemoveRange(db.MeasurementValues.Where(x => testValueIds.Contains(x.Id)));
        db.MeasurementBatches.RemoveRange(db.MeasurementBatches.Where(x => testBatchIds.Contains(x.Id)));
        db.StationOperationSessions.RemoveRange(db.StationOperationSessions.Where(x => testSessionIds.Contains(x.Id)));
        db.ProductStationItems.RemoveRange(db.ProductStationItems.Where(x =>
            testProducts.Contains(x.ProductId) || testStations.Contains(x.StationId) || testItems.Contains(x.InspectionItemId)));
        db.WorkOrders.RemoveRange(db.WorkOrders.Where(x => testWorkOrders.Contains(x.Id)));
        db.InspectionItems.RemoveRange(db.InspectionItems.Where(x => testItems.Contains(x.Id)));
        db.Stations.RemoveRange(db.Stations.Where(x => testStations.Contains(x.Id)));
        db.Products.RemoveRange(db.Products.Where(x => testProducts.Contains(x.Id)));
        await db.SaveChangesAsync();

        return new ClearTestDataResponse(
            testProducts.Count,
            testStations.Count,
            testItems.Count,
            testWorkOrders.Count,
            testSessionIds.Count,
            testBatchIds.Count,
            testValueIds.Count,
            testAlertIds.Count);
    }

    public async Task EnsureSpcRulesAsync()
    {
        var groupCode = "WE";
        var group = await db.SpcRuleGroups.FirstOrDefaultAsync(x => x.RuleGroupCode == groupCode);
        if (group == null)
        {
            group = new SpcRuleGroup
            {
                RuleGroupCode = groupCode,
                RuleGroupName = "Western Electric Rules (西方電氣規則)",
                Description = "系統預設 8 大 SPC 管制規則庫。",
                IsEnabled = true
            };
            db.SpcRuleGroups.Add(group);
            await db.SaveChangesAsync();
        }
        else
        {
            group.RuleGroupName = "Western Electric Rules (西方電氣規則)";
            group.Description = "系統預設 8 大 SPC 管制規則庫。";
            group.IsEnabled = true;
        }

        var existingRules = await db.SpcRules.Where(x => x.RuleGroupId == group.Id).Select(x => x.RuleCode).ToListAsync();

        var rulesToAdd = new List<SpcRule>();
        if (!existingRules.Contains("Rule1_Over3Sigma"))
            rulesToAdd.Add(new SpcRule { RuleGroupId = group.Id, RuleCode = "Rule1_Over3Sigma", RuleName = "規則 1：單點超出 3 Sigma 管制界限", Priority = 10 });
        if (!existingRules.Contains("Rule2_9SameSide"))
            rulesToAdd.Add(new SpcRule { RuleGroupId = group.Id, RuleCode = "Rule2_9SameSide", RuleName = "規則 2：連續 9 點落在中心線同一側", RuleConfigJson = "{\"RequiredPoints\":9}", Priority = 20 });
        if (!existingRules.Contains("Rule3_6Trend"))
            rulesToAdd.Add(new SpcRule { RuleGroupId = group.Id, RuleCode = "Rule3_6Trend", RuleName = "規則 3：連續 6 點持續上升或下降", RuleConfigJson = "{\"RequiredPoints\":6}", Priority = 30 });
        if (!existingRules.Contains("Rule4_14Alternating"))
            rulesToAdd.Add(new SpcRule { RuleGroupId = group.Id, RuleCode = "Rule4_14Alternating", RuleName = "規則 4：連續 14 點上下交替", RuleConfigJson = "{\"RequiredPoints\":14}", Priority = 40 });
        if (!existingRules.Contains("Rule5_2Of3Over2Sigma"))
            rulesToAdd.Add(new SpcRule { RuleGroupId = group.Id, RuleCode = "Rule5_2Of3Over2Sigma", RuleName = "規則 5：連續 3 點中有 2 點超出 2 Sigma 且同側", Priority = 50 });
        if (!existingRules.Contains("Rule6_4Of5Over1Sigma"))
            rulesToAdd.Add(new SpcRule { RuleGroupId = group.Id, RuleCode = "Rule6_4Of5Over1Sigma", RuleName = "規則 6：連續 5 點中有 4 點超出 1 Sigma 且同側", Priority = 60 });
        if (!existingRules.Contains("Rule7_15Within1Sigma"))
            rulesToAdd.Add(new SpcRule { RuleGroupId = group.Id, RuleCode = "Rule7_15Within1Sigma", RuleName = "規則 7：連續 15 點落在中心線 1 Sigma 內", Priority = 70 });
        if (!existingRules.Contains("Rule8_8Outside1Sigma"))
            rulesToAdd.Add(new SpcRule { RuleGroupId = group.Id, RuleCode = "Rule8_8Outside1Sigma", RuleName = "規則 8：連續 8 點落在中心線兩側且都超出 1 Sigma", Priority = 80 });

        if (rulesToAdd.Count > 0)
        {
            db.SpcRules.AddRange(rulesToAdd);
            await db.SaveChangesAsync();
        }
    }

    public async Task<ClearAllDataResponse> ClearAllDatabaseDataAsync()
    {
        // 1. Transactional/Operation Data (Deletions order: Children first)
        int lotSlotHistories = await db.LotSlotHistories.ExecuteDeleteAsync();
        int slotParameters = await db.SlotParameters.ExecuteDeleteAsync();
        int lotSplitHistories = await db.LotSplitHistories.ExecuteDeleteAsync();
        
        // Break self-reference on LotMaster
        await db.LotMasters.ExecuteUpdateAsync(s => s.SetProperty(l => l.ParentLotId, (long?)null));
        int lotMasters = await db.LotMasters.ExecuteDeleteAsync();
        
        int variableMeasurements = await db.VariableMeasurements.ExecuteDeleteAsync();
        int attributeMeasurements = await db.AttributeMeasurements.ExecuteDeleteAsync();
        int spcCalculationResults = await db.SpcCalculationResults.ExecuteDeleteAsync();
        
        int uploadErrors = await db.UploadErrors.ExecuteDeleteAsync();
        int uploadDetails = await db.UploadDetails.ExecuteDeleteAsync();
        int uploadBatches = await db.UploadBatches.ExecuteDeleteAsync();
        
        int alertEvents = await db.AlertEvents.ExecuteDeleteAsync();
        
        int measurementValues = await db.MeasurementValues.ExecuteDeleteAsync();
        int measurementBatches = await db.MeasurementBatches.ExecuteDeleteAsync();
        int stationOperationSessions = await db.StationOperationSessions.ExecuteDeleteAsync();
        int workOrders = await db.WorkOrders.ExecuteDeleteAsync();
        int mesSyncMessages = await db.MesSyncMessages.ExecuteDeleteAsync();

        // 2. Master/Configuration Data (Deletions order: Children first)
        int partProcessCharacteristics = await db.PartProcessCharacteristics.ExecuteDeleteAsync();
        int productStationItems = await db.ProductStationItems.ExecuteDeleteAsync();
        int machines = await db.Machines.ExecuteDeleteAsync();
        int qualityCharacteristics = await db.QualityCharacteristics.ExecuteDeleteAsync();
        int slots = await db.Slots.ExecuteDeleteAsync();
        int tanks = await db.Tanks.ExecuteDeleteAsync();
        int productionLines = await db.ProductionLines.ExecuteDeleteAsync();
        int factories = await db.Factories.ExecuteDeleteAsync();
        int plants = await db.Plants.ExecuteDeleteAsync();
        int parts = await db.Parts.ExecuteDeleteAsync();
        int processes = await db.Processes.ExecuteDeleteAsync();
        int spcRules = await db.SpcRules.ExecuteDeleteAsync();
        int spcRuleGroups = await db.SpcRuleGroups.ExecuteDeleteAsync();
        int controlChartTypes = await db.ControlChartTypes.ExecuteDeleteAsync();
        int controlChartCategories = await db.ControlChartCategories.ExecuteDeleteAsync();
        int controlChartGroups = await db.ControlChartGroups.ExecuteDeleteAsync();
        int formulaDefinitions = await db.FormulaDefinitions.ExecuteDeleteAsync();
        int inspectionItems = await db.InspectionItems.ExecuteDeleteAsync();
        int stations = await db.Stations.ExecuteDeleteAsync();
        int products = await db.Products.ExecuteDeleteAsync();
        
        int units = await db.Units.ExecuteDeleteAsync();
        int shifts = await db.Shifts.ExecuteDeleteAsync();
        int operators = await db.Operators.ExecuteDeleteAsync();
        int customers = await db.Customers.ExecuteDeleteAsync();
        int suppliers = await db.Suppliers.ExecuteDeleteAsync();
        int chemicals = await db.Chemicals.ExecuteDeleteAsync();

        return new ClearAllDataResponse(
            lotSlotHistories,
            slotParameters,
            lotSplitHistories,
            lotMasters,
            variableMeasurements,
            attributeMeasurements,
            spcCalculationResults,
            uploadErrors,
            uploadDetails,
            uploadBatches,
            alertEvents,
            measurementValues,
            measurementBatches,
            stationOperationSessions,
            workOrders,
            mesSyncMessages,
            partProcessCharacteristics,
            productStationItems,
            machines,
            qualityCharacteristics,
            slots,
            tanks,
            productionLines,
            factories,
            plants,
            parts,
            processes,
            spcRules,
            spcRuleGroups,
            controlChartTypes,
            controlChartCategories,
            controlChartGroups,
            formulaDefinitions,
            inspectionItems,
            stations,
            products,
            units,
            shifts,
            operators,
            customers,
            suppliers,
            chemicals
        );
    }
}

